<?
$PERM["lichnyy-kabinet-prodavtsa"]["2"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["6"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["9"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["2"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="D";
$PERM["ads"]["9"]="W";
$PERM["services"]["9"]="W";
$PERM["products"]["9"]="W";
$PERM["o-servise"]["9"]="W";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["9"]="D";
$PERM["news"]["9"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["9"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["9"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["9"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>