<?
$PERM["products"]["9"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["9"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["9"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["9"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["9"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["9"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>